module.exports = {
  // server port
  port: 3000,

  // title
  title: "s-parallax-component",

  // layout
  layout: "right",

  // compile server
  compileServer: {
    // compile server port
    port: 4000
  },

  // editors
  editors: {
    html: {
      language: "html",
      data: `
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <s-parallax mouse-x="300" mouse-y="300" scroll-y="200" min-y="0">
          <img src="https://source.unsplash.com/random/300x300" />
        </s-parallax>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <s-parallax scroll-y="300" min-y="0" applier="!background" style="background-image: url(https://source.unsplash.com/random); background-size: cover; height:300px; width:100%;"></s-parallax>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <s-parallax layer="test">
          <img src="https://source.unsplash.com/random/300x300" />
        </s-parallax>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
        <p class="p m-b">
          Potenti sem mollis senectus est integer morbi congue suspendisse amet, non dolor nulla tincidunt volutpat commodo nam varius venenatis, posuere himenaeos ad sapien ipsum lacinia lacus donec. Mus sed montes dapibus arcu nunc, nostra natoque porta hac. Parturient interdum euismod ut magnis maecenas curabitur viverra lorem primis donec pharetra, feugiat in mollis netus nibh convallis libero purus neque cursus. Maecenas et vitae non facilisi elementum nisl, libero orci eleifend diam aptent inceptos, ipsum suspendisse lacinia faucibus curabitur. Aptent fames ultricies elementum nullam pharetra commodo interdum, mus lectus pretium hendrerit at eros nec, conubia nisi neque montes dictum mattis. Curabitur etiam proin et eros placerat potenti sed adipiscing metus vel, nibh parturient dictum facilisis commodo egestas porttitor tempor cubilia maecenas ridiculus, facilisi massa cras nam sagittis suspendisse mattis venenatis ultrices. Ligula phasellus sed in cubilia sodales torquent massa quisque sollicitudin congue metus pharetra erat fermentum facilisis, bibendum semper elit imperdiet curae eros arcu accumsan ridiculus lectus inceptos consectetur vel.
        </p>
      `
    },
    css: {
      language: "scss",
      data: `
        @import 'node_modules/coffeekraken-sugar/index';
        @import 'node_modules/coffeekraken-s-typography-component/index';
        @include s-init();
        @include s-classes();
        @include s-typography-classes();
        body {
          padding: s-space(bigger);
        }
      `
    },
    js: {
      language: "js",
      data: `
        import SParallaxComponent from './dist/index'
      `
    }
  }
}
